### ISSUE TITLE
Tests fail with Python 3.6.0

### ISSUE THREAD

**Issue by AndrewTorrance** [ONSdigital/sdc-cryptography#16]
Pass with 3.4.5 . 
3 tests all with same error 
======================================================================
ERROR: crypto.test.test_jwt_helper (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: crypto.test.test_jwt_helper
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/andrewtorrance/projects/sdc-cryptography/sdc/crypto/test/test_jwt_helper.py", line 6, in <module>
    from sdc.crypto.jwt_helper import JWTHelper
  File "/Users/andrewtorrance/projects/sdc-cryptography/sdc/crypto/jwt_helper.py", line 4, in <module>
    from jwcrypto import jwt
  File "/Users/andrewtorrance/.virtualenvs/sdc-cryptography/lib/python3.6/site-packages/jwcrypto/jwt.py", line 9, in <module>
    from jwcrypto.jwe import JWE
  File "/Users/andrewtorrance/.virtualenvs/sdc-cryptography/lib/python3.6/site-packages/jwcrypto/jwe.py", line 8, in <module>
    from jwcrypto.jwa import JWA
  File "/Users/andrewtorrance/.virtualenvs/sdc-cryptography/lib/python3.6/site-packages/jwcrypto/jwa.py", line 10, in <module>
    from cryptography.hazmat.primitives import constant_time, hashes, hmac
  File "/Users/andrewtorrance/.virtualenvs/sdc-cryptography/lib/python3.6/site-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: dlopen(/Users/andrewtorrance/.virtualenvs/sdc-cryptography/lib/python3.6/site-packages/_cffi_backend.cpython-36m-darwin.so, 2): Symbol not found: _PySlice_AdjustIndices
  Referenced from: /Users/andrewtorrance/.virtualenvs/sdc-cryptography/lib/python3.6/site-packages/_cffi_backend.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/andrewtorrance/.virtualenvs/sdc-cryptography/lib/python3.6/site-packages/_cffi_backend.cpython-36m-darwin.so

**Comment by JamesGardiner** [comment]
To fix this, either do a `pip install -i -U -r requirements.txt` or create a new virtualenv and do `make build`
